### ISSUE TITLE
Disable style injection

### ISSUE THREAD

**Issue by Mushr0000m** [mikhailvs/vue-calendar-input#3]
Hi,

Your component looks exactly what I need, but can you add an attribute to disable style injection ?

Thanks

**Comment by mikhailvs** [comment]
Hey. Can you elaborate a bit on what you mean by disabling style injection? Are you saying you want a way to have no default styling?

**Comment by Mushr0000m** [comment]
To have no default style used for the component to use only my own.

Also is there a way to set the locale to use for the dates (month names etc) ?

**Comment by mikhailvs** [comment]
I see. Can you help me understand the use case for this? All the classes are documented, so you can override them for your custom styling.

As far as locale goes, there isn't currently support built in, but you can use the header, dayName, and day slots to inject localized headings.

**Comment by Mushr0000m** [comment]
About the styling it's because if we use multiples components and each component include styling, it's all that unwanted code that get to the browser, it's not has optimized has it can be if we don't need it. It's more a general concern to just have what we use. Same goes for not having to override style when we could just write style.

For the locale it's more for the month names, maybe in a config object or something. Anyway, great component.
